#Course : CS 513 - Knowledge discovery and Data mining
#Course Instructor:- Khashayar Dehnad
#First Name: Keval
#Last Name: Sompura
#Id: 20033127
#Assignment: 03 - KNN
#Description: Using KNN to develop a classification model

In [574]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [575]:
headers = ["SampleCode", "ClumpThickness", "UniformityCellSize", "UniformityCellShape", "MarginalAdhesion", "SingleEpithelialCellSize", "BareNuclei", "BlandChromatin", "NormalNucleoli", "Mitoses", "Class"]

In [576]:
folder='C:/Users/Asus/OneDrive/Stevens/Sem-2/KDDM/HW3/'
file='breast-cancer-wisconsin.csv'
data = pd.read_csv(folder+file, header=None,skiprows=1, names=headers,na_values='?')
data.head()

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0     1000025               5                   1                    1   
1     1002945               5                   4                    4   
2     1015425               3                   1                    1   
3     1016277               6                   8                    8   
4     1017023               4                   1                    1   

   MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                 1                         2         1.0               3   
1                 5                         7        10.0               3   
2                 1                         2         2.0               3   
3                 1                         3         4.0               3   
4                 3                         2         1.0               3   

   NormalNucleoli  Mitoses  Class  
0               1        1      2  
1               2        1      2  
2               1        1      2  
3               7        1      2  
4               1        1      2

In [577]:
data = data.dropna()
data

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0       1000025               5                   1                    1   
1       1002945               5                   4                    4   
2       1015425               3                   1                    1   
3       1016277               6                   8                    8   
4       1017023               4                   1                    1   
..          ...             ...                 ...                  ...   
694      776715               3                   1                    1   
695      841769               2                   1                    1   
696      888820               5                  10                   10   
697      897471               4                   8                    6   
698      897471               4                   8                    8   

     MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                   1                         2         1.0               3   
1                   5                         7        10.0               3   
2                   1                         2         2.0               3   
3                   1                         3         4.0               3   
4                   3                         2         1.0               3   
..                ...                       ...         ...             ...   
694                 1                         3         2.0               1   
695                 1                         2         1.0               1   
696                 3                         7         3.0               8   
697                 4                         3         4.0              10   
698                 5                         4         5.0              10   

     NormalNucleoli  Mitoses  Class  
0                 1        1      2  
1                 2        1      2  
2                 1        1      2  
3                 7        1      2  
4                 1        1      2  
..              ...      ...    ...  
694               1        1      2  
695               1        1      2  
696              10        2      4  
697               6        1      4  
698               4        1      4  

[683 rows x 11 columns]

In [578]:
data['Class'] = data['Class'].map({2: 'Benign', 4: 'Malignant'}).fillna(data['Class'])
data

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0       1000025               5                   1                    1   
1       1002945               5                   4                    4   
2       1015425               3                   1                    1   
3       1016277               6                   8                    8   
4       1017023               4                   1                    1   
..          ...             ...                 ...                  ...   
694      776715               3                   1                    1   
695      841769               2                   1                    1   
696      888820               5                  10                   10   
697      897471               4                   8                    6   
698      897471               4                   8                    8   

     MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                   1                         2         1.0               3   
1                   5                         7        10.0               3   
2                   1                         2         2.0               3   
3                   1                         3         4.0               3   
4                   3                         2         1.0               3   
..                ...                       ...         ...             ...   
694                 1                         3         2.0               1   
695                 1                         2         1.0               1   
696                 3                         7         3.0               8   
697                 4                         3         4.0              10   
698                 5                         4         5.0              10   

     NormalNucleoli  Mitoses      Class  
0                 1        1     Benign  
1                 2        1     Benign  
2                 1        1     Benign  
3                 7        1     Benign  
4                 1        1     Benign  
..              ...      ...        ...  
694               1        1     Benign  
695               1        1     Benign  
696              10        2  Malignant  
697               6        1  Malignant  
698               4        1  Malignant  

[683 rows x 11 columns]

In [579]:
X = data.drop(columns=['SampleCode', 'Class'])
y = data['Class']


In [580]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [581]:
X = pd.DataFrame(MinMaxScaler().fit_transform(X), columns=X.columns)

In [582]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)


In [583]:
knn_3 = KNeighborsClassifier(n_neighbors=3)
knn_5 = KNeighborsClassifier(n_neighbors=5)
knn_10 = KNeighborsClassifier(n_neighbors=10)

In [584]:
knn_3.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [585]:
knn_5.fit(X_train,y_train)


KNeighborsClassifier()

In [586]:
knn_10.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [587]:
y_pred_3 = knn_3.predict(X_test)
y_pred_5 = knn_5.predict(X_test)
y_pred_10 = knn_10.predict(X_test)

In [588]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [589]:
conf_matrix_3 = confusion_matrix(y_test, y_pred_3)
print(conf_matrix_3)

[[130   1]
 [  2  72]]


In [590]:
conf_matrix_5 = confusion_matrix(y_test, y_pred_5)
print(conf_matrix_5)

[[129   2]
 [  2  72]]


In [591]:
conf_matrix_10 = confusion_matrix(y_test, y_pred_10)
print(conf_matrix_10)

[[128   3]
 [  3  71]]


In [592]:
accuracy_3 = accuracy_score(y_test, y_pred_3) * 100
print(f'Accuracy of KNN-3: {accuracy_3:.2f}%')

Accuracy of KNN-3: 98.54%


In [593]:
accuracy_5 = accuracy_score(y_test, y_pred_5) * 100
print(f'Accuracy of KNN-5: {accuracy_5:.2f}%')

Accuracy of KNN-5: 98.05%


In [594]:
accuracy_10 = accuracy_score(y_test, y_pred_10) * 100
print(f'Accuracy of KNN-10: {accuracy_10:.2f}%')

Accuracy of KNN-10: 97.07%


In [595]:
from sklearn.metrics import classification_report

In [596]:
classify_report_3 = classification_report(y_test, y_pred_3)
print(classify_report_3)

              precision    recall  f1-score   support

      Benign       0.98      0.99      0.99       131
   Malignant       0.99      0.97      0.98        74

    accuracy                           0.99       205
   macro avg       0.99      0.98      0.98       205
weighted avg       0.99      0.99      0.99       205



In [597]:
classify_report_5 = classification_report(y_test, y_pred_5)
print(classify_report_5)

              precision    recall  f1-score   support

      Benign       0.98      0.98      0.98       131
   Malignant       0.97      0.97      0.97        74

    accuracy                           0.98       205
   macro avg       0.98      0.98      0.98       205
weighted avg       0.98      0.98      0.98       205



In [598]:
classify_report_10 = classification_report(y_test, y_pred_10)
print(classify_report_10)

              precision    recall  f1-score   support

      Benign       0.98      0.98      0.98       131
   Malignant       0.96      0.96      0.96        74

    accuracy                           0.97       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.97      0.97      0.97       205

