In [10]:
#Course : CS 513 - Knowledge discovery and Data mining
#Course Instructor:- Khashayar Dehnad
#First Name: Keval
#Last Name: Sompura
#Id: 20033127
#MidTerm Exam: Q5

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [12]:
folder='C:/Users/Asus/OneDrive/Stevens/Sem-2/KDDM/Mid Term/'
file='hepatitis_B2.csv'
data = pd.read_csv(folder+file)
data.head()

Class  AGE  SEX  STEROID  ANTIVIRALS  FATIGUE  MALAISE  ANOREXIA  \
0      1   39    1        1           1        1        1         2   
1      1   37    1        2           2        1        2         2   
2      1   58    1        2           2        1        2         2   
3      1   30    1        2           2        1        1         1   
4      1   38    1        1           2        1        1         1   

   LIVER_BIG  LIVER_FIRM  SPLEEN_PALPABLE  SPIDERS  ASCITES   VARICES  \
0          2           1                2        2        2         2   
1          2           2                2        1        2         2   
2          1           1                1        1        2         2   
3          2           1                2        1        1         1   
4          2           1                2        1        1         1   

   BILIRUBIN  ALK_PHOSPHATE  SGOT  ALBUMIN  HISTOLOGY Age_Quartile  
0        2.3            280    98      3.8          1           Q2  
1        0.6             67    28      4.2          1           Q2  
2        2.0            167   242      3.3          1           Q4  
3        2.5            165    64      2.8          2           Q1  
4        1.2            118    16      2.8          2           Q2

In [13]:
#check null values
data.isnull().sum()

Class              0
AGE                0
SEX                0
STEROID            0
ANTIVIRALS         0
FATIGUE            0
MALAISE            0
ANOREXIA           0
LIVER_BIG          0
LIVER_FIRM         0
SPLEEN_PALPABLE    0
SPIDERS            0
ASCITES            0
 VARICES           0
BILIRUBIN          0
ALK_PHOSPHATE      0
SGOT               0
ALBUMIN            0
HISTOLOGY          0
Age_Quartile       0
dtype: int64

In [14]:
X = data[['AGE', 'SEX', 'ASCITES', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN']]
y = data['Class']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=55)

In [16]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
k_value = 1
print(f"K-Value: {k_value}")
knn_model = KNeighborsClassifier(n_neighbors=k_value)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
model_accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {model_accuracy:.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")

K-Value: 1
Accuracy: 0.7500
Precision: 0.7714
Recall: 0.7500
F1-score: 0.7556

Classification Report:
              precision    recall  f1-score   support

           1       0.86      0.75      0.80         8
           2       0.60      0.75      0.67         4

    accuracy                           0.75        12
   macro avg       0.73      0.75      0.73        12
weighted avg       0.77      0.75      0.76        12

Confusion Matrix:
[[6 2]
 [1 3]]



In [18]:
k_value = 3
print(f"K-Value: {k_value}")
knn_model = KNeighborsClassifier(n_neighbors=k_value)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
model_accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {model_accuracy:.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")

K-Value: 3
Accuracy: 0.6667
Precision: 0.6667
Recall: 0.6667
F1-score: 0.6667

Classification Report:
              precision    recall  f1-score   support

           1       0.75      0.75      0.75         8
           2       0.50      0.50      0.50         4

    accuracy                           0.67        12
   macro avg       0.62      0.62      0.62        12
weighted avg       0.67      0.67      0.67        12

Confusion Matrix:
[[6 2]
 [2 2]]



In [19]:
k_value = 5
print(f"K-Value: {k_value}")
knn_model = KNeighborsClassifier(n_neighbors=k_value)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
model_accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {model_accuracy:.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")

K-Value: 5
Accuracy: 0.9167
Precision: 0.9333
Recall: 0.9167
F1-score: 0.9185

Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.88      0.93         8
           2       0.80      1.00      0.89         4

    accuracy                           0.92        12
   macro avg       0.90      0.94      0.91        12
weighted avg       0.93      0.92      0.92        12

Confusion Matrix:
[[7 1]
 [0 4]]



In [20]:
k_value = 7
print(f"K-Value: {k_value}")
knn_model = KNeighborsClassifier(n_neighbors=k_value)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
model_accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {model_accuracy:.4f}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted'):.4f}")
print(f"F1-score: {f1_score(y_test, y_pred, average='weighted'):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}\n")

K-Value: 7
Accuracy: 0.8333
Precision: 0.8889
Recall: 0.8333
F1-score: 0.8381

Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.75      0.86         8
           2       0.67      1.00      0.80         4

    accuracy                           0.83        12
   macro avg       0.83      0.88      0.83        12
weighted avg       0.89      0.83      0.84        12

Confusion Matrix:
[[6 2]
 [0 4]]

